### ISSUE TITLE
setup script fails on ubuntu 16.04/18.04

### ISSUE THREAD

**Issue by jotego** [kevinpt/opbasm#24]
May I suggest adding this line to the README file?

To install on Linux run:
**sudo python setup.py install**
Then use **opbasm** to run the program.

For people like me, who are not regular python users, this kind of help is needed.
Thanks.

**Comment by Paebbels** [comment]
@jotego  
This is already documented in opbasm's [documentation](http://kevinpt.github.io/opbasm) - section [installation](http://kevinpt.github.io/opbasm/#installation).

**Comment by jotego** [comment]
You are right. Thank you very much and apologies. I had actually looking through the documentation first before deciding to download it.
